apiVersion: dcn.ssu.ac.kr/v1
kind: QuotaAutoscaler
metadata:
  name: quota-autoscaler
  namespace: default # kpt-set: ${namespace}
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  behavior:
    scaleDown:
      policies:
        - method: cpu
          value: 30
          targetUtilization: 50
        - method: memory
          value: 30
          targetUtilization: 50
    scaleUp:
      policies:
        - method: cpu
          value: 70
          targetUtilization: 50
        - method: memory
          value: 70
          targetUtilization: 50
  min.cpu: "4"
  max.cpu: "25"
  min.memory: "4Gi"
  max.memory: "25Gi"
