apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: default # kpt-set: ${namespace}
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
