apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotascale-controller
  namespace: quotascale-controller # kpt-set: ${namespace}
  labels:
    app.kubernetes.io/name: quotascale-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quotascale-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quotascale-controller
      annotations:
        quotascale.dcn.ssu.ac.kr/image-revision: "2268934" # kpt-set: ${image-revision}
    spec:
      serviceAccountName: quotascale-controller-sa
      terminationGracePeriodSeconds: 6
      containers:
        - name: quotascale-controller
          image: jangwonlee/quotascale-controller:latest # kpt-set: ${image-quotascale-controller}
          imagePullPolicy: Always # kpt-set: ${image-pull-policy}
          args:
            - --enable-node-scaling=true # kpt-set: ${enable-node-scaling-arg}
            - --quota-check-interval=10s # kpt-set: ${quota-check-interval-arg}
            - --quota-update-interval=10s # kpt-set: ${quota-update-interval-arg}
            - --node-scaling-repo-url=http://13.212.192.49:32100/nephio/workload-cluster.git # kpt-set: ${node-scaling-repo-url-arg}
            - --node-scale-in-delay=10s # kpt-set: ${node-scale-in-delay-arg}
            - --node-scale-in-exempt-namespaces=longhorn-system,metallb-system # kpt-set: ${node-scale-in-exempt-namespaces-arg}
            - --node-scaling-prepared-spares=2 # kpt-set: ${node-scaling-prepared-spares-arg}
            - --node-scaling-activated-spares=1 # kpt-set: ${node-scaling-activated-spares-arg}
            - --enable-node-scale-in-force=false # kpt-set: ${enable-node-scale-in-force-arg}
          env:
            - name: GITEA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: quotascale-git-credentials # kpt-set: ${gitops-secret-name}
                  key: username
            - name: GITEA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quotascale-git-credentials # kpt-set: ${gitops-secret-name}
                  key: password
          resources:
            requests:
              cpu: 200m # kpt-set: ${cpu-request}
              memory: 2Gi # kpt-set: ${memory-request}
            limits:
              cpu: "2" # kpt-set: ${cpu-limit}
              memory: 2Gi # kpt-set: ${memory-limit}
