apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: quotascale-controller
  image-quotascale-controller: ghcr.io/ssu-dcn/quotascale-controller:latest
  image-pull-policy: IfNotPresent
  quota-check-interval-arg: --quota-check-interval=1m
  quota-update-interval-arg: --quota-update-interval=1m
  enable-node-scaling-arg: --enable-node-scaling=false
  cpu-request: 200m
  memory-request: 2Gi
  cpu-limit: "2"
  memory-limit: 2Gi
